Repository spryker-eco/adyen, pull requests merged in 2020-12, with the labels that each got.

#26 TE-6081 FE CSS Lazy Load
  src/SprykerEco/Yves/Adyen/Theme/default/components/molecules/adyen-credit-card/index.ts
  src/SprykerEco/Yves/Adyen/Theme/default/components/molecules/credit-card/index.ts
Labels: ready-for-release

#28 CC-11193 adyen direct debit payment non empty validation
  src/SprykerEco/Yves/Adyen/Form/CreditCardSubForm.php
  src/SprykerEco/Yves/Adyen/Form/DirectDebitSubForm.php
Labels: bug

#30 Release 1.6
  src/SprykerEco/Client/Adyen/Zed/AdyenStub.php
  src/SprykerEco/Yves/Adyen/Form/CreditCardSubForm.php
  src/SprykerEco/Yves/Adyen/Form/DirectDebitSubForm.php
  src/SprykerEco/Yves/Adyen/Theme/default/components/molecules/adyen-credit-card/index.ts
  src/SprykerEco/Yves/Adyen/Theme/default/components/molecules/credit-card/index.ts
  src/SprykerEco/Zed/Adyen/Business/Order/AdyenOrderPaymentManager.php
  src/SprykerEco/Zed/Adyen/Persistence/Propel/Schema/spy_payment_adyen.schema.xml
Labels: improvement, request-review

#32 Fixed amount field length.
  src/SprykerEco/Zed/Adyen/Persistence/Propel/Schema/spy_payment_adyen.schema.xml
Labels: bug
